

services:
  postgres:
    image: postgres:17.2
    container_name: file_sharing_postgres
    environment:
      POSTGRES_USER: file_sharing_service
      POSTGRES_PASSWORD: offer_from_doczilla
      POSTGRES_DB: file_sharing_service
    ports:
      - "5445:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U file_sharing_service"]
      interval: 5s
      timeout: 5s
      retries: 5